# Generated by Django 3.1.7 on 2025-12-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utas', models.CharField(max_length=20, verbose_name='Утасны дугаар')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('buten_ner', models.CharField(max_length=100, verbose_name='Бүтэн нэр')),
                ('hotiin_ner', models.CharField(blank=True, max_length=50, null=True)),
                ('sumiin_ner', models.CharField(blank=True, max_length=50, null=True)),
                ('bagiin_ner', models.CharField(blank=True, max_length=50, null=True)),
                ('letter', models.TextField(blank=True, null=True, verbose_name='Захидал')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ebarimt_picture', models.FileField(upload_to='ebarimt_pictures/')),
                ('status', models.CharField(default='draft', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Lottery',
                'verbose_name_plural': 'Lotteries',
                'db_table': 'lottery',
                'ordering': ['-created_at'],
            },
        ),
    ]
